ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS PAID BOOLEAN      NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS RESERVED BOOLEAN      NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS CANCELLATION_REASON VARCHAR(50);

UPDATE orders SET status = 'NEW' WHERE status IN ('PAYMENT_PENDING', 'PAID');

